version: '3'

volumes:
  pg_data:
  static:
  media:
  sqlite3:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: crocko/tortuga_backend
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
      - sqlite3:/sqlite3
    depends_on:
      - db
  gateway:
    image: crocko/tortuga_gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - backend
